# Generated by Django 4.2.30 on 2026-06-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0007_add_salarys'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_booking',
            name='Room_No',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
