# Generated by Django 4.2.30 on 2026-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0008_online_booking_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_employee',
            name='Dateof_Birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='add_employee',
            name='Joining_Date',
            field=models.DateField(),
        ),
    ]
