# Generated by Django 6.0.6 on 2026-06-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0009_alter_add_employee_dateof_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offline_booking',
            name='Upload_Image',
        ),
        migrations.RemoveField(
            model_name='online_booking',
            name='Img',
        ),
        migrations.AlterField(
            model_name='add_employee',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_employee',
            name='Email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='add_employee',
            name='Guardian_Number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='add_employee',
            name='Mobile_Number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='add_employee',
            name='Personal_Identity',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='add_employee',
            name='Upload_Image',
            field=models.ImageField(upload_to='employees/'),
        ),
        migrations.AlterField(
            model_name='add_room',
            name='Room_Image',
            field=models.ImageField(upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='add_room',
            name='Room_Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_salarys',
            name='Email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='add_salarys',
            name='Salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='authorregis',
            name='Phone_Number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='offline_booking',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offline_booking',
            name='Check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offline_booking',
            name='Check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offline_booking',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offline_booking',
            name='Mobile_Number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='offline_booking',
            name='Personal_Identity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Nid_No',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Phone_Number',
            field=models.BigIntegerField(),
        ),
    ]
