# Generated by Django 6.0.6 on 2026-06-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0010_remove_offline_booking_upload_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_room',
            name='Status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied'), ('Dirty', 'Dirty'), ('Maintenance', 'Maintenance')], default='Vacant', max_length=20),
        ),
        migrations.AddField(
            model_name='offline_booking',
            name='Status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=20),
        ),
        migrations.AddField(
            model_name='online_booking',
            name='Status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=20),
        ),
    ]
