# Generated by Django 6.0.6 on 2026-06-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0011_add_room_status_offline_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_room',
            name='Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Occupied', 'Occupied'), ('Dirty', 'Dirty'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance'), ('Out of Service', 'Out of Service')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='offline_booking',
            name='Status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Confirmed', 'Confirmed'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Reserved', max_length=20),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Status',
            field=models.CharField(choices=[('Inquiry', 'Inquiry'), ('Reserved', 'Reserved'), ('Confirmed', 'Confirmed'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Reserved', max_length=20),
        ),
        migrations.CreateModel(
            name='GuestCharge',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Charge_Type', models.CharField(choices=[('Room', 'Room'), ('Restaurant', 'Restaurant'), ('Laundry', 'Laundry'), ('Conference', 'Conference'), ('Other', 'Other')], max_length=50)),
                ('Description', models.CharField(max_length=255)),
                ('Amount', models.IntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Offline_Booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.offline_booking')),
                ('Online_Booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.online_booking')),
            ],
        ),
        migrations.CreateModel(
            name='GuestPayment',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount_Paid', models.IntegerField()),
                ('Payment_Method', models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('Receipt_Number', models.CharField(max_length=100, unique=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Offline_Booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.offline_booking')),
                ('Online_Booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.online_booking')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Issue', models.CharField(max_length=255)),
                ('Priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], default='Medium', max_length=20)),
                ('Status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('Assigned_To', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_Reported', models.DateField(auto_now_add=True)),
                ('Date_Resolved', models.DateField(blank=True, null=True)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.add_room')),
            ],
        ),
    ]
