# Generated by Django 6.0.6 on 2026-06-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0012_alter_add_room_status_alter_offline_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorregis',
            name='Role',
            field=models.CharField(choices=[('Receptionist', 'Receptionist'), ('Housekeeper', 'Housekeeper'), ('Manager', 'Manager'), ('Administrator', 'Administrator')], default='Receptionist', max_length=20),
        ),
    ]
