# Generated by Django 6.0.6 on 2026-06-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0013_authorregis_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authorregis',
            new_name='AuthorRegistration',
        ),
    ]
