# Generated by Django 6.0.6 on 2026-06-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0014_rename_authorregis_authorregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_Salarys',
            new_name='EmployeeSalary',
        ),
        migrations.AlterModelTable(
            name='employeesalary',
            table='Employee_Salaries',
        ),
    ]
